init:
  - git config --global core.autocrlf input

shallow_clone: true

version: '{build}'

skip_tags: true

environment:
  GH_ACCESS_TOKEN:
    secure: 4ghR4B22y08Vjex2N9eTuXOaWaK4qSHu+AxEjF/jAQ6GRLXW7Mog1sWxYb6un3C2

install:
  - ps: Install-Product node 2
  - npm install

build: off

before_test:
  - git config --global user.name "Shinnosuke Watanabe"
  - git config --global user.email "snnskwtnb@gmail.com"

test_script:
  - npm run-script test-only

cache:
  - node_modules -> package.json
